runtime: python27
api_version: 1
threadsafe: true
libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11
builtins:
- deferred: on

handlers:
# API
#- url: /_ah/spi/.i*
- url: /_ah/api/.*
  script: api_main.handle
# Task Queue
- url: /_ah/queue/deferred
  login: admin
  script: google.appengine.ext.deferred.application
  secure: always
# Static assets
- url: /css
  static_dir: css
- url: /js/layout
  static_dir: js/layout
- url: /fonts
  static_dir: fonts
- url: /images
  static_dir: images
# Train timeline retriever
- url: /retrieve/.*
  script: utils.cronJob.app
  login: admin
# Batch tasks
- url: /batch/(.+)
  script: utils.batch.batchJob
  login: admin
# Console
- url: /console
  script: main.app
  login: admin
# Main WEB site
- url: /.*
  script: main.app
