application: disco-parsec-749
version: 1
runtime: python27
api_version: 1
threadsafe: true
builtins:
- deferred: on

handlers:
- url: /_ah/queue/deferred
  login: admin
  script: google.appengine.ext.deferred.application
  secure: always
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /fonts
  static_dir: fonts
- url: /images
  static_dir: images
# Train timeline retriever
- url: /retrieve/.*
  script: utils.cronJob.app
  login: admin
# Batch tasks
- url: /batch/(.+)
  script: utils.batch.batchJob
  login: admin
# Console
- url: /console/.*
  script: main.app
# Main WEB site
- url: /survey
  script: main.app
- url: /.*
  script: main.app
