application: disco-parsec-749
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /fonts
  static_dir: fonts
- url: /images
  static_dir: images
- url: /.*/css
  static_dir: css
- url: /.*/js
  static_dir: js
- url: /.*/fonts
  static_dir: fonts
- url: /.*/images
  static_dir: images
- url: /batch
  script: croneTabPage.app
  login: admin
- url: /survey/.*
  script: stats.app
- url: /survey
  script: stats.app
- url: /.*
  script: home.app